package com.lhfeiyu.business.model;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.parent_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.priority
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private Short priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.status
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.create_user_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.create_user_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.create_date
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.edit_user_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private Long editUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.edit_user_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private String editUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.edit_date
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    private Date editDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.parent_id
     *
     * @return the value of category.parent_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.parent_id
     *
     * @param parentId the value for category.parent_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.priority
     *
     * @return the value of category.priority
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public Short getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.priority
     *
     * @param priority the value for category.priority
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setPriority(Short priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.status
     *
     * @return the value of category.status
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.status
     *
     * @param status the value for category.status
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.create_user_id
     *
     * @return the value of category.create_user_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.create_user_id
     *
     * @param createUserId the value for category.create_user_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.create_user_name
     *
     * @return the value of category.create_user_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.create_user_name
     *
     * @param createUserName the value for category.create_user_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.create_date
     *
     * @return the value of category.create_date
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.create_date
     *
     * @param createDate the value for category.create_date
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.edit_user_id
     *
     * @return the value of category.edit_user_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public Long getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.edit_user_id
     *
     * @param editUserId the value for category.edit_user_id
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setEditUserId(Long editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.edit_user_name
     *
     * @return the value of category.edit_user_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public String getEditUserName() {
        return editUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.edit_user_name
     *
     * @param editUserName the value for category.edit_user_name
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setEditUserName(String editUserName) {
        this.editUserName = editUserName == null ? null : editUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.edit_date
     *
     * @return the value of category.edit_date
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.edit_date
     *
     * @param editDate the value for category.edit_date
     *
     * @mbg.generated Wed May 29 13:35:25 CST 2019
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }
}